"""Render the autoloaded API-coverage doc from the inventory + coverage map.

Grouped by tag: every operation with its status (covered / pending / not_planned /
deprecated) and owning tool(s). Lives in rossum-reference/ so it surfaces into
every Claude session — uncovered operations read as "exists in API, no tool yet".
"""
from __future__ import annotations

from collections import defaultdict

from . import coverage

_MARK = {"covered": "✅", "pending": "⬜", "not_planned": "🚫", "deprecated": "⚠️"}


def render_coverage_doc(inventory: list[dict], coverage_map: dict) -> str:
    rows_by_tag: dict[str, list] = defaultdict(list)
    counts: dict[str, int] = defaultdict(int)
    for op in sorted(inventory, key=lambda o: (o["tag"], o["path"], o["method"])):
        endpoint = f"{op['method']} {coverage._display_path(op['path'])}"
        entry = coverage_map.get(endpoint)
        decision = entry["decision"] if entry else "pending"
        tools = ", ".join(entry.get("tools", [])) if entry else ""
        counts[decision] += 1
        rows_by_tag[op["tag"]].append((endpoint, decision, tools))

    head = f"**{counts['covered']} covered · {counts['pending']} pending"
    if counts.get("not_planned"):
        head += f" · {counts['not_planned']} not planned"
    if counts.get("deprecated"):
        head += f" · {counts['deprecated']} deprecated"
    head += f" · {len(inventory)} total operations**"

    lines = [
        "# Rossum API coverage", "",
        "_Auto-generated — do not edit by hand. Tracks which Rossum API operations the "
        "`rossum-api` MCP server wraps. Regenerated by `scripts/bootstrap_coverage.py` and "
        "the scheduled coverage workflow. ⬜ pending = exists in the API, no MCP tool yet._",
        "", head, "",
    ]
    for tag in sorted(rows_by_tag):
        lines += [f"## {tag}", "", "| Operation | Status | Tool(s) |", "|---|---|---|"]
        for endpoint, decision, tools in rows_by_tag[tag]:
            lines.append(f"| `{endpoint}` | {_MARK.get(decision, '')} {decision} | {tools} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
