"""Render the autoloaded API-coverage doc from the inventory + coverage map.

Grouped by tag: every operation with its status (covered / via rossum_get / pending /
not_planned / deprecated) and owning tool(s). Lives in rossum-reference/ so it surfaces
into every Claude session — uncovered operations read as "exists in API, no tool yet".
"""
from __future__ import annotations

from collections import defaultdict

from . import coverage

_MARK = {"covered": "✅", "implicit": "✅", "pending": "⬜",
         "not_planned": "🚫", "deprecated": "⚠️"}
_LABEL = {"implicit": "via rossum_get"}


def render_coverage_doc(inventory: list[dict], coverage_map: dict) -> str:
    rows_by_tag: dict[str, list] = defaultdict(list)
    counts: dict[str, int] = defaultdict(int)
    for op in sorted(inventory, key=lambda o: (o["tag"], o["path"], o["method"])):
        endpoint = f"{op['method']} {coverage._display_path(op['path'])}"
        entry = coverage_map.get(endpoint)
        if entry:
            decision = entry["decision"]
            tools = ", ".join(entry.get("tools", []))
        elif op["method"] == "GET":
            decision = "implicit"
            tools = "rossum_get"
        else:
            decision = "pending"
            tools = ""
        counts[decision] += 1
        rows_by_tag[op["tag"]].append((endpoint, decision, tools))

    head = (f"**{counts['covered']} covered · {counts['implicit']} via rossum_get · "
            f"{counts['pending']} pending")
    if counts.get("not_planned"):
        head += f" · {counts['not_planned']} not planned"
    if counts.get("deprecated"):
        head += f" · {counts['deprecated']} deprecated"
    head += f" · {len(inventory)} total operations**"

    lines = [
        "# Rossum API coverage", "",
        "_Auto-generated — do not edit by hand. Tracks which Rossum API operations the "
        "`rossum-api` MCP server wraps. Regenerated by `scripts/bootstrap_coverage.py` and "
        "the scheduled coverage workflow. ⬜ pending = uncovered write, no MCP tool yet. ✅ via rossum_get = readable through the generic rossum_get tool (no dedicated tool)._",
        "", head, "",
    ]
    for tag in sorted(rows_by_tag):
        lines += [f"## {tag}", "", "| Operation | Status | Tool(s) |", "|---|---|---|"]
        for endpoint, decision, tools in rows_by_tag[tag]:
            label = _LABEL.get(decision, decision)
            lines.append(f"| `{endpoint}` | {_MARK.get(decision, '')} {label} | {tools} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
